version: '3.1'
services:
  mysql-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin-container:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-container
      - PMA_USER=root
      - PMA_PASSWORD=pass

  expense-tracker:
    image: expense-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/expenses
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      - mysql-container

volumes:
  mysql-data:
