version: '3.1'
services:
  localhost:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=expenses
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin-container:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-container
      - PMA_USER=root
      - PMA_PASSWORD=pass

  expense-tracker:
    build:
      context: .
    image: expense-tracker
    ports:
      - "8081:80"
    depends_on:
      - localhost
volumes:
    mysql-data:

